all:
  hosts:
    node1:
      ansible_host: masterip
      ip: masterip
      access_ip: masterip
    node2:
      ansible_host: worker01ip
      ip: worker01ip
      access_ip: worker01ip
    
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
